import React from 'react'
import TopNavbar from '../../Components/Layout/TopNavbar';
import Head from 'next/head';
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import Footer from '../../Components/Layout/Footer';


export default function Landing({ children }) {
    
    return (
        <>
            <Head>
                <title>NTowels</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopNavbar />
            <main>
                {children}
            </main>

            <Footer />
        </>
    )
}
